name: update daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    
    permissions:  # 添加必要的权限
      contents: write  # 允许写入仓库
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}  # 使用GITHUB_TOKEN认证

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests urllib3 zip

    - name: Extract and save IP list
      run: |
        bash updatedaily.sh

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        git add text_files.zip
        if ! git diff-index --quiet HEAD --; then
          git commit -m "Auto-update IP list [skip ci]"
          git push origin HEAD:main
          echo "Changes pushed successfully"
        else
          echo "No changes to commit"
        fi
